#!/bin/sh
#

apk add nginx

chmod +x /tmp/entrypoint

cp -av /tmp/entrypoint /sbin/
cp -av /tmp/nginx.conf /etc/nginx/http.d/default.conf

######

cd /var/www

if [ ! -d /var/www/api ]; then
    wget https://github.com/imsyy/DailyHotApi/archive/refs/heads/master.tar.gz
    tar xvf master.tar.gz && mv DailyHotApi-master api
    rm -f master.tar.gz
fi

cd /var/www/api

sed -i "s|parent:|title:|" routes/ngabbs.js
sed -i 's|\$(this)|\$(e)|g' routes/ithome.js
sed -i 's|each(()|each((i,e)|g' routes/ithome.js

[ -d node_modules ] || npm i

######

cd /var/www

if [ ! -d /var/www/web ]; then
    wget https://github.com/imsyy/DailyHot/archive/refs/heads/master.tar.gz
    tar xvf master.tar.gz && mv DailyHot-master web
    rm -f master.tar.gz
fi

cp -av /tmp/web/* web/

cd /var/www/web

sed -i "s|Copyright By|$(date +'%Y')|" src/components/Footer.vue
sed -i 's|"author": "imsyy"|"author": "APP_COPYRIGHT"|' package.json
sed -i 's|"github": "https://github.com/imsyy"|"github": "APP_COPYRIGHT_URL"|' package.json

echo "VITE_GLOBAL_API=/api" >.env
echo "VITE_ICP=APP_ICP" >>.env
echo "VITE_DIR=/" >>.env

[ -d node_modules ] || npm i
[ -d dist ] || npm run build

mv dist /var/www/webui
rm -rf /var/www/web

######

rm -rf /tmp/*
